export const LEVELS = {
    1: {
        monitorText: 'Welcome to the test lab subject #8X75G2, please proceed to the right to begin testing...',
        tileArray: ['#####################',
        '#####               #',
        '#                   #',
        '#                   #',
        '#          s        #',
        '#          #        #',
        '#                   e',
        '#####################']
    },
    2: {
        monitorText: 'For each test all we need to do is make it to the other side of the room...',
        tileArray: ['#####################',
                    '#####               #',
                    '#                   #',
                    '#                   #',
                    '#            #      #',
                    '#          ###      #',
                    '#s       #####      e',
                    '#####################']
    },
    3: {
        monitorText: 'To move back and forth in the current room use the arrow keys to your advantage...               Wait until Im done talking jeez...',
        tileArray: ['#####################',
                    '#####               #',
                    '#                   #',
                    '#                   #',
                    '#                   e',
                    '#              ###  #',
                    '#s           # # # ##',
                    '#####################']
    },
    4: {
        monitorText: 'Money is tight so if you are dumb enough to fall in a hole we will just get a new test subject...',
        tileArray: ['#####################',
                    '#####               #',
                    '#                   #',
                    '#                   #',
                    '#                   #',
                    '#                   #',
                    '#s                  e',
                    '##########  #########']
    },
    5:{
        monitorText: 'Focus on a pad by pressing F and you should be able to change colors.',
        tileArray: ['#####################',
                    '#####               e',
                    '#                   #',
                    '#                   #',
                    '#                   #',
                    '#                   #',
                    '#s                  #',
                    '######r##############']
    },
    6:{
        monitorText: 'Thats a big hole... hot damn. Being pink gives you a double jump btw...',
        tileArray: ['#####################',
                    '#####               #',
                    '#                   #',
                    '#                   #',
                    '#                   #',
                    '#                   #',
                    '#s                  e',
                    '######p###     ######']
    },
    7:{
        monitorText: 'yellow on the other hand gives you the ability to dash with the D button',
        tileArray: ['#####################',
                    '#####    #    #     #',
                    '#        #    #     #',
                    '#        #    #     #',
                    '#        #    #     #',
                    '#        ######     #',
                    '#s                  e',
                    '######y## ## # ######']
    },
    8:{
        monitorText: 'Press space to turn blue so you can reabsorb another color',
        tileArray: ['#####################',
                    '#####     #####     #',
                    '#                   #',
                    '#              #    #',
                    '#        y     #    #',
                    '#        #     #    #',
                    '#s       #     #    e',
                    '######p###     ######']
    },
    9:{
        monitorText: 'Now this is testing so we have been scoring you and tracking your vitals... Here they are.',
        tileArray: ['#####################',
                    '#####               #',
                    '#         #         e',
                    '#      #  #  #      #',
                    '#   #     #        ##',
                    '#   ###   #    #    #',
                    '#s#     #           #',
                    '#####################']
    },
    10:{
        monitorText: 'This is extremely important!!! Those pointy things will rip chunks off of you. If you get small enough you will die.',
        tileArray: ['#####################',
                    '#####               #',
                    '#                   #',
                    '#                   #',
                    '#                   #',
                    '#                   #',
                    '#s#                 #',
                    '#######^^^#########e#']
    },
    11:{
        monitorText: 'Good luck not getting hurt lmao...',
        tileArray: ['#####################',
                    '#####               #',
                    '#                   #',
                    '#                   #',
                    '#                   #',
                    '#                   #',
                    '#s#         ^       #',
                    '#######^^^^#^^#####e#']
    },
    12:{
        monitorText: 'Green pads are a one time use but will restore you a bit of health',
        tileArray: ['#####################',
                    '#####               #',
                    '#                   #',
                    '#                   #',
                    '#                   #',
                    '#                   #',
                    '#s                  #',
                    '#######g###########e#']
    },
    13:{
        monitorText: 'Sometimes dying a little bit can help ya out...',
        tileArray: ['##########################',
                    '#####                    #',
                    '#                        #',
                    '#                        #',
                    '#                        #',
                    '#                        #',
                    '#                        #',
                    '#                        #',
                    '#                        #',
                    '#                        #',
                    '#                        #',
                    '#                        #',
                    '#                        #',
                    '#                        #',
                    '#                        #',
                    '#                        #',
                    '######                   #',
                    '#    ###                 #',
                    '#  s                     #',
                    '#^######################e#']
    },
    14:{
        monitorText: 'Only gets harder from here...',
        tileArray: ['##########################',
        '#####                    #',
        '#                        #',
        '#                        #',
        '#                        #',
        '#                        #',
        '#                        #',
        '#                        #',
        '#           ##           #',
        '#                        #',
        '#      ##                #',
        '#                        #',
        '#  ##                    #',
        '#                        #',
        '#      ##                #',
        '#                        #',
        '######                   #',
        '#    ###                 #',
        '#  s     #               #',
        '#########           ####e#']
    },
    15:{
        monitorText: 'Gonna leave you alone for a bit now... Good luck...',
        tileArray: ['##########################',
        '#####                    #',
        '#                        #',
        '#                        #',
        '#          ^^^^          #',
        '#y#                      #',
        '#        ^               #',
        '#        ^               #',
        '#        ^               #',
        '#        ^               #',
        '#      ##^               #',
        '#        ^               #',
        '#  ##    ^               #',
        '#        ^               #',
        '#      ##^               #',
        '#        ^               #',
        '######   ^               #',
        '#    ##^ ^               #',
        '#  s     ^               #',
        '###p######          ##g#e#']

    }
}


tileArray: ['#####################',
                    '#####               #',
                    '#                   #',
                    '#                   #',
                    '#          s        #',
                    '#          #        #',
                    '#                   e',
                    '#####################']